webpack/webpack-dev-middleware

middleware.js

When bundle is large, I download the script using XMLHttpRequest, so
that the download progress can be monitored.
During development, to test that this works requires that Content-Length
header be sent in the dev server.

add Content-Length header to response

---

README.md
middleware.js

Use case:
```js
watchOptions: {
poll: true
}
```
in `webpack.config.js`.
This is analogous to the deprecation in the `webpack` CLI.
See https://github.com/webpack/webpack/blob/89058a2c4a32a2ec31c88acb3789c4f9eda58db1/bin/convert-argv.js#L84 and https://github.com/webpack/webpack/blob/89058a2c4a32a2ec31c88acb3789c4f9eda58db1/lib/webpack.js#L35

Use watchOptions instead of solely allowing watchDelay

---

middleware.js

Hello. I would be grateful if you could check this out and hopefully merge it at your earliest convenience, as I make heavy use of webpack-dev-server, and this bug is actually quite difficult to work around if you rely on HTML5-style pushState routing.
Many thanks.
Fixes #54.

Fix serving index.html on Windows

---

middleware.js

use res.send instead of res.end to enable etag.

use res.send instead of res.end to enable etag.

---

middleware.js

Revert's https://github.com/webpack/webpack-dev-middleware/pull/27
Assuming https://github.com/webpack/webpack-dev-middleware/issues/58 is correct, I'm just adding a PR to revert.
Otherwise feel free to ignore/close.

use res.end: reverting #27

---

middleware.js

I started the `webpack-dev-server` in lazy mode with the following arguments `--lazy --iframe --progress --colors`. My webpack.config.js looks like this:
```
'use strict';
var path = require('path');
module.exports = {
entry: [
'./app/index'
],
output: {
path: path.join(__dirname, 'build'),
filename: 'bundle.js',
publicPath: '/static/'
}
};
```
I got 404 error for bundle.js. After some debugging it turned out that this expression `(!options.filename || options.filename.test(filename))` on line 150 evaluates to `false` because `filename` variable equals to "/bundle.js" (with a forward slash). So I changed options.filename regex to allow optional forward slash and everything works now correctly.

Allow slash in filename regex

---

middleware.js
package.json

Seeking through media, such as audio and video, often leads a browser
to make range requests, in addition to other scenarios. Responding with
the full content instead of the requested range and can lead to
unexpected behaviour in a web application that in production will
otherwise work since the production server supports range requests.
- Depend on range-parser to parse range request headers
- Use source from the `send` npm package on responding to range
requests https://github.com/pillarjs/send/blob/31ceb6aaf530152c29a1855bf3f9dbd86533303e/index.js#L551-L583

Support Range requests commonly used by media

---

middleware.js

when I use koa to serve webpack-dev-middleware, it will always return 404
because this line
https://github.com/koajs/koa/blob/master/lib/application.js#L133
but body return normally(after rebuild assets, so url is different)

set statusCode to 200 to capable of koa 

---

README.md

publicPath should be stated as required, as also described on the webpack docs: [https://webpack.github.io/docs/webpack-dev-middleware.html](url)
I think this can avoid confusion for beginners.

readme.md change: publicPath should be stated as required

---

middleware.js

Usage:
```js
app.use(webpackDevMiddleware(compiler, {
reporter: ({ state, stats, options }) => {
console.log('log what you want')
}
}))
```
Example reporter:
```js
const oraReporter = () => {
const spinner = ora()
spinner.start()
return ({ state, stats }) => {
if (state) {
const durations = stats.endTime - stats.startTime
const formatedDurations = durations >= 1000 ? `${durations / 1000} s` : `${durations} ms`
const message = `Completed in ${formatedDurations.magenta}`
if (stats.hasErrors() || stats.hasWarnings()) {
spinner.clear()
const { errors, warnings } = stats.compilation
errors.concat(warnings).forEach(warning => {
console.log(warning.message)
})
}
spinner.text = message
} else {
spinner.text = 'Building...'
}
}
}
```

Reporter option

---

middleware.js

Doesn't make sense to for the middleware on all routes.

Only use middleware for 'GET' requests

---

.travis.yml
README.md
middleware.js

In order to use this middleware to develop a server-side rendering application, we need access to the [`stats`](https://github.com/webpack/docs/wiki/node.js-api#stats). This PR is aimed to give the access to consumers.
```JavaScript
app.use(webpackMiddleware(compiler, { serverSideRender: true })
app.use((req, res) => {
const  assetsByChunkName = res.locals.webpackStats.toJson().assetsByChunkName
// then use `assetsByChunkName` for server-sider rendering
})
```
If `options.serverSideRender` is true, the __webpack-dev-middleware__ will set the `stat` object, which is generated by the latest build, to `res.locals`, then call `next()` to trigger the next middleware. 
During the webpack building process, all requests, inclusive of non-files request, will be pending until the build is finished.

Support for server-side rendering 

---

middleware.js

Given that `state` should always have the correct value (if the bundle is valid
or not) then we should be able to use ready directly without checking the
watcher.
I also hit a bug where the watcher had running set to false while the bundle was
invalid, leading to a callback being executed immediately instead of waiting.
Fixes #107

Removing watching/watching.running check

---

middleware.js

I wasn't sure if I should open an issue or a pull request, but since I already made some changes, here goes.
I have perhaps a peculiar use case: I want to use the middleware for multiple express apps that would share a single compiler but otherwise be independent and listen on different ports and serve different index files that would include different bundles (webpack is configured with multiple entry points).
The problem arises because the middleware mutates the compiler.outputFileSystem property. When setting up multiple middlewares only the last one will be valid and the ones before will hold a reference to a memory fs that the compiler is not using to write files to.
My solution was to detect if the outputFileSystem already was a MemoryFileSystem and if it was, just not overwrite it …

Instantiate MemoryFileSystem only once

---

middleware.js
test/Reporter.test.js

By allowing overrides of the functions used for logging, we can allow the output from this middleware to be processed according to the logging library used in the application.

Make log & warn functions replaceable

---

middleware.js
test/API.test.js

As discussed in https://github.com/webpack/webpack-dev-middleware/issues/126

Expose stats

---

lib/GetFilenameFromUrl.js
test/GetFilenameFromUrl.test.js

Pass `true` for `slashesDenoteHost` in `url.parse`.
https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost
Fixes #128

Fix protocol-relative urls with `publicPath`

---

middleware.js

options.warn is called before a default is set if options.watchDelay is a thing.

Set default reporter, log, and warn

---

middleware.js
test/Server.test.js

Fixes https://github.com/webpack/webpack-dev-server/issues/432
This hasn't broken anything for me.

Added charset=UTF-8 to content-type to fix encoding issues.

---

lib/Shared.js
middleware.js

Leaving this here to get your impression of this approach. Using it, it would be fairly simple to add an additional interface to the module. One which simply takes a file name and returns the bundle content.

factor out shareable methods to a common class

---

lib/Shared.js
test/CompilerCallbacks.test.js
test/Lazy.test.js

Bugfix
Yes.
**Summary**
See #156. When the compiler wanted to report an error in the bundle (e.g. because of a plugin), it would throw the error and quit the process.
I've changed this to work more like the [webpack watch mode](https://github.com/webpack/webpack/blob/287eb18076d80688be03a55431918b628b25f436/bin/webpack.js#L302-L303); it shows the error with `console.error` but it keeps running (because the error can be fixed with a new compilation).
Optionally, it's possible to hide / customize this error by using `options.error`.
Not really; previously the process would quit and now it doesn't.
Fixes #156

Fix error handling in compiler `watch()` and `run()`

---

package.json

Expand the peer dependency option to include webpack 2 rc
No
**Summary**
Peer dependency errors are thrown by package managers, as the current version does not allow webpack 2 rc
No

Allow webpack 2 RC

---

lib/Shared.js
test/Reporter.test.js

Change, a small improvement in DX.
Yes
**Summary**
When the bundle is compiling, the console showed this:
```
webpack: bundle is now INVALID.
```
When it is done compiling, regardless of errors, it showed this:
```
webpack: bundle is now VALID.
```
This is very confusing, because most people think when it is "valid", that the bundle has successfully compiled. Also, when it says "bundle is now INVALID", people can think they have done something wrong.
<hr>
This PR indents to clarify these messages;
When the bundle is compiling:
```
webpack: Compiling...
```
When the bundle is done compiling, but has errors:
```
webpack: Failed to compile.
```
When the bundle is done compiling, no errors:
```
webpack: …
```

Improve messages when bundle is compiling and done with compiling

---

lib/GetFilenameFromUrl.js
test/GetFilenameFromUrl.test.js

Bugfix.
Yes.
**Summary**
This PR fix getFilenameFromUrl output result. 
getFilenameFromUrl function does not properly parse url with spaces.
It is happens because url.parse return encoded pathname.
Look screenshot please:
So getFilenameFromUrl can't return right filename that contains spaces.
My approach is decode final output again.
It's shouldn't.

Fix parsing urls with spaces. Use decodeURIComponent for getFilenameFromUrl final output

---

middleware.js

Related to webpack/webpack-dev-middleware#174

Avoid setting http status code explicitly

---

README.md

Documentation
N/A
**Summary**
I was following the examples and realized that it only works if you have more than one `main` bundle (such as js and on css bundle). Adding this one-liner makes it work with or without the extra `main` bundle. This small change also works when adding other named bundles (which would more than likely be single files - **non array**), and supports turning on source maps (which would make the named assets value into arrays).
Additionally, the interpolated values were returning arrays and were not being properly formatted. Therefore, I added a `.join('\n')` call at the end.
No

Make serverSideRendering example work consistently

---

README.md
lib/Shared.js
middleware.js
test/Server.test.js

Please look here https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L65:
```js
res.setHeader("Content-Type", mime.lookup(filename) + "; charset=UTF-8");
```
The line above detemine the mimeType of file, but I have a special file, Index.phtml, so I have to defining custom mimeType
Example:
```js
app.use(webpackMiddleware(webpack({
// webpack options
// webpackMiddleware takes a Compiler object as first parameter
// which is returned by webpack(...) without callback.
entry: "...",
output: {
path: "/"
// no real path is required, just pass "/"
// but it will work with other paths too.
}
}), {
// ......
mimeTypes: {
'text/html': ['phtml']
}
}));
```

Add a option, mimeTypes, to support defining custom mime types

---

lib/Shared.js
test/Reporter.test.js

When the compilation fails or has warnings, the compilation
messages are outputted in console.log not using the options.error
and options.warn functions.
This commit change the defaultReporter to output the stats
and final message to the options.error when the compilation
has errors or the options.warn when it has warnings.
The Reporter.test.js test cases are updated accordingly.

Use options.log, warn and error for compilation messages

---

lib/GetFilenameFromUrl.js
test/GetFilenameFromUrl.test.js

This PR fixes cases like https://github.com/facebookincubator/create-react-app/issues/2439 where the filepath contains characters normally considered malformed in URIs such as '%'.
As stated in the [docs](https://nodejs.org/api/querystring.html):
> By default, the querystring.unescape() method will attempt to use the JavaScript built-in decodeURIComponent() method to decode. If that fails, a safer equivalent that does not throw on malformed URLs will be used.
This PR adds a test that confirms that `%` now works on filenames and paths. However, the fix can still give false positives for things like '%bar%' where `%ba` ends up being escaped as percent encoded characters, but I think those are edge cases …

Use querystring.unescape to fallback to safer equivalent that does not throw on malformed URIs

---

README.md
middleware.js
test/Server.test.js

Resolves https://github.com/webpack/webpack-dev-middleware/issues/153, see the discussion there.
New logic for requests that resolve to a directory:
1. If `options.index` is `true` or `undefined`, attempt to serve `index.html`
2. If `options.index` is falsy, do not serve anything
3. Otherwise, serve `options.index`

Stop serving index.html if options.index is falsy

---

package.json
test/CompilerCallbacks.test.js

fix desperation method.
**Summary**
`sandbox.stub(obj, 'meth', val)` is deprecated and will be removed from the public API in a future version of sinon.
Use `sandbox.stub(obj, 'meth').callsFake(fn)` instead in order to stub a function.
Use `sandbox.stub(obj, 'meth').value(fn)` instead in order to stub a non-function value.

fix sinon desperation

---

lib/Shared.js
middleware.js
package.json
test/Server.test.js

Adds support for correctly serving .wasm files when using webpack/next WebAssembly support
yes
**Summary**
Changes middleware so it does not add charset to application/wasm MIME type, which solves #229
No

serve .wasm files as application/wasm (without charset)

---

breaking-changes.md

Looking at the `package.json` it seems that the correct logging lib is [`loglevel`](https://www.npmjs.com/package/loglevel). This can be important, because there is actually a package called [`log-level`](https://www.npmjs.com/package/log-level) as well 😁

fixed name of logging lib and added link

---

.editorconfig
README.md
index.js
lib/context.js

An inconvenience/bug fix and introduction of a new option.
n/a
**Summary**
This mimics the fix found in [ff0000-ad-tech/wp-plugin-watch-offset](ff0000-ad-tech/wp-plugin-watch-offset) which was the result of a long-standing bug in `watchpack` in [webpack/watchpack/issues/25](https://github.com/webpack/watchpack/issues/25). It resolves the endless - or random multiple - compile issue by advancing the time for watching and stats startTime. This is introduced through the `watchOffset` option, which can be set to `0` to disable prevention and restore original behavior. 
I do not believe so. It's unlikely.

prevent multiple identical compilations via watch startTime

---

lib/util.js
test/tests/util.js

Fixes #255 by using only the path part of `compilerPublicPath` for checking against `url`.
Tests were added which correspond to existing tests for the same functionality.
**Summary**
This fixes an issue I was seeing with `webpack-dev-server` where it would not select the correct compiler from the list to serve the bundle.
I don't think this should introduce a breaking change since the use case this addresses currently does not work.

Fix getPaths for publicPaths that are URLs (#255)

---

lib/util.js
test/fixtures/server-test/webpack.client.server.config.js
test/tests/server.js

Fixes #258.
Yes, both 200 and 404 cases.
**Summary**
This fixes a crash when accessing a path outside of publicPath, in a multi-compiler setup, when one of the compiler configs does not include a publicPath. This can occur when using universal rendering through https://github.com/60frames/webpack-hot-server-middleware.
No.

fixes #258: skip compilers with no publicPath

---

lib/util.js
test/tests/util.js

Bug fix for #270 .
Test added for the Windows path that will be generated after this fix.
Where we might expect `c:\foo\bar` we instead get a URL-ized `c://\foo/bar`. Either works with the default path translation on Windows, though *technically* it's wrong.
**Summary**
Allows using webpack-dev-middleware on Windows. Without this, the path generated is along the lines of `/c:\foo/bar` which is then translated by Windows as `c:\c:\foo\bar` under the hood, which won't resolve properly.
Not that I'm aware of. It's possible that someone using a very non-idiomatic path on a POSIX system might have problems, maybe.
I wouldn't call this the …

Fix Windows Paths

---

lib/util.js
test/test.js
test/tests/util.js

Bugfix
Yes
**Summary**
fixes #284, on windows path spaces should resolve to %20
For implementations relying on the bug, possibly.
This PR is WIP until this line is removed, as changes will be pushed to the target branch for AppVeyor to compile, as I don't have access to Windows at the moment.

On windows path spaces should resolve to %20

---

lib/fs.js
package-lock.json
package.json

A refactor
No need
**Summary**
There's some controversy over which kind of dependency `chalk` should be and its use. `webpack-log` now exports `chalk` as a dependency for one-off use.
No

refactor: use chalk from webpack-log

---

lib/fs.js
test/fixtures/server-test/webpack.array.config.js
test/tests/server.js

This is a bugfix 🐛🔫 for #290 😸. I'm running into the same problem these days.
Yes, I've added a test in `test/tests/server.js`
**Summary**
Fix the exception thrown when [`writeToDisk`](https://github.com/webpack/webpack-dev-middleware/pull/287) is enabled in multi-compiler mode.
No.

Fix the exception thrown when `writeToDisk` is enabled in multi-compiler mode

---

README.md

Change to the SSR example in the README
tests not required
**Summary**
when following this example for SSR I added a check for the case in `normalizeAssets` whereby an object will be converted to an array. This makes sense for the purpose when your webpack entry is an object. Then you will get an array of paths.
no
I'm not an expert and maybe there is an edge case where this method is unsuitable, but it works for my use case and would maybe help someone else too

updates example - catches the case whereby assets are an object

---

package.json

Update webpack-log dependency to 1.2.0

---

lib/fs.js
lib/util.js
package-lock.json
package.json

Removes the `path-is-absolute` dependency, since `path.isAbsolute` is natively supported on all `node` versions now
- None

refactor(package): remove `path-is-absolute` dependency (`dependencies`)

---

README.md
lib/middleware.js
test/tests/server.js

feature
yes
**Summary**
In order for the next middleware in line to be able to use the memory FileSystem created by `webpack-dev-middleware` (and access the files generated in memory by the compilation process) this commit passes the context.fs to the res.locals along with webpackStats when ServerSideRender is set to true.
No
This is a PR is contingent on ServerSideRender not being removed from the middleware

feat(middleware): expose the memory filesystem to other middlewares (`response.locals.fs`)

---

lib/middleware.js
lib/util.js
package-lock.json
package.json
test/tests/util.js

fix: replace `url-join` with `path.posix.join`

---

lib/middleware.js
test/tests/server.js

fixes: #354
bugfix
Of course!
**Summary**
Do not pass 'null' as media-type when mime-type lookup fails.
See #354 
No

fix(middleware): do not add 'null' to Content-Type

---

lib/fs.js
test/fixtures/server-test/webpack.querystring.config.js
test/tests/server.js

This is a bug fix to bring file writing behavior closer to that of webpack and the WriteFilePlugin.
Yes
**Summary**
Webpack and the WriteFilePlugin cut off filenames at the first ?, so you can use filenames like `'[name].js?[contenthash]'` without writing hashes to your filesystem. This updates the dev middleware to do the same when `writeToDisk` is enabled.
If you were using writeToDisk with a ? in `output.filename` then you won't end up with a ? in filenames on disk any more. If you pass a filter function to `writeToDisk` then that function will also stop getting the querystring.
Here's where querystrings get cut off in webpack and …

Remove querystring from filenames when writing to disk

---

lib/middleware.js
test/tests/server.js

Bugfix. #350
Less aggressive alternative to PR #351 
Yes
**Summary**
Creates a variable to special case more file types that should not automatically have a charset added to their content-type header.  This was already the case for wasm and this also adds usdz.
No
I originally attempted to look up each filetype in mime-db (#351) to determine if it should receive a charset.  However, that only looks up if the file type has a "default" charset defined by the spec which is not necessarily good for friendly out-of-the box support and could have introduced breaking changes.

Don't add charset to certain file types

---

README.md
lib/fs.js
test/tests/file-system.js

* fs option which can be used to configure non-default file system
(it is forced to use `memory-fs` instead currently)
**What are use cases?**
* The same as for middleware, but with opportunity to use other memory file systems (like [memfs](https://github.com/streamich/memfs))
* adds couple of tests
**Summary**
* Solves longstanding problem of not having opportunity to use other non-memory-fs libraries and configure it manually either via `webpackCompiler.outputFileSystem` or `middleware(..., ..., { fs: fileSystem }`
* Negative

Configurable file system via options.fs

---

lib/middleware.js
test/tests/server.js

When the Content-Type header is already present (for example it has been 
set by other middleware) we do not overwrite it.
Yes, added unit test to the suite.
**Summary**
Closes #376
No

Do not overwrite Content-Type

---

test/tests/server.js

Bugfix for https://github.com/webpack/webpack-dev-middleware/pull/377#issuecomment-470170219
Yes, in test suite.
**Summary**
The headers get set *after* Content-Type already got overwritten. Hence 
the test is not testing whether the Content-Type overwrite is actually 
skipped.
No

Fix overwrite Content-Type test

---

lib/fs.js
package-lock.json
package.json

Fixes Webpack 5 usage by no longer requiring the removed webpack/lib/node/NodeOutputFileSystem
Fixes #435.
Introduces dependency on `mkdirp`, which was only transient through `webpack` before.

fix: directly used mkdirp instead of through Webpack

---

azure-pipelines.yml
lib/fs.js
test/fixtures/server-test/webpack.array.config.js
test/fixtures/server-test/webpack.client.server.config.js
test/fixtures/server-test/webpack.config.js
test/fixtures/server-test/webpack.querystring.config.js
test/server.test.js

ci: webpack@5 test

---

lib/fs.js
test/fixtures/server-test/webpack.client.server.config.js
test/fixtures/server-test/webpack.config.js
test/fixtures/server-test/webpack.querystring.config.js
test/server.test.js

compatibility with latest webpack@5
No
webpack@5 has regression in `invalidate` method, so temporary comment some part of test (already written to sokra about this)
Also many test uses `context: '/'`, it is invalid, context should be full path to directory.
This code:
```js
// TODO Why? Need remove in future major release
if (outputPath === '/') {
outputPath = compiler.context;
}
```
just workaround with invalid tests, i don't know why previously developer do this, maybe he did not understand or did not know how to write tests, this will remain a mystery to us

fix: compatibility with webpack@5

---

index.js

refactor: simplify code

---

README.md
src/index.js
src/middleware.js
src/utils/setupOutputFileSystem.js
test/server.test.js

Better API and use name as used in webpack, improve locals access because other middlewares can setup `fs` too and it is break app, better use this under `webpack` property
Yes
- the `fs` option was renamed to the `outputFileSystem` option. 
- the `fileSystem` property was removed from API, please use `context.outputFileSystem` instead. 
- the middleware `locals` now under `res.locals.webpack` - use `res.locals.webpack.stats` for access stats and `res.locals.webpack.outputFileSystem` for access `outputFileSystem`.
No

Refactor fs

---

src/index.js
src/middleware.js
src/utils/ready.js
src/utils/setupHooks.js

Rename `webpackStats` to `stats` because `webpack` prefix is unnecessary
Yes
I will write tests after https://github.com/webpack/webpack-dev-middleware/pull/494, also we don't have tests on this right now

Refactor rename webpack stats to stats

---

src/utils/setupWriteToDisk.js

resolve todo
No
It is invalid logic, we should respect `output.path` as is

refactor: resolve todo

---

src/utils/setupOutputFileSystem.js
test/middleware.test.js

compiler.outputPath === option.path from configuration https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L61
webpack already validate that option (only an absolute path allowed) - https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L1309
No
No

refactor: remove unnecessary error

---

src/utils/setupOutputFileSystem.js
test/middleware.test.js

The `outputFileSystem` option doesn't work in multi-compiler mode.
No
No

Fix output file system in multi compiler mode

---

src/middleware.js
test/middleware.test.js

Some exceptions still can be throw in `readFileSync`, it is hard to implement in tested environment, but I just use `spy` to reproduce
No
No

fix: handle exceptions for reading files

---

README.md
package-lock.json
package.json
src/index.js
src/middleware.js
test/middleware.test.js
test/validation-options.test.js

fixes #350
Yes
- Do not add `utf-8` to requests with custom MIME types
- Do not add `utf-8` to requests which can be non `utf-8`
- The `mimeTypes` option was changed - no the `force` option, you need specify `extension` and `type`
- migrate on `mime-types` because `mime` is deprecated
- refactor tests

Refactor migrate on mime types

---

README.md
package.json
src/middleware.js
src/utils/getFilenameFromUrl.js
test/api.test.js
test/middleware.test.js
test/utils/getFilenameFromUrl.test.js

Changes:
- respect `publicPath` value from `output.path`
- fix using `[hash]`/`[fullhash]` in `output.path` and `output.publicPath` options
- fix broken test
- remove invalid check on `HASH`, a developer can use any filename for any files
- we need use `stats` to get output path and public path
Yes, default value of `publicPath` is `output.publicPath`
We recommend use a same value for `publicPath` and for `output.publicPath` so let's do it by default for 0CJS https://github.com/webpack/webpack-dev-middleware#publicpath

Refactor get filename from url

---

package-lock.json
package.json
src/index.js
src/middleware.js
src/utils/getFilenameFromUrl.js
src/utils/getPossibleFilePaths.js
test/api.test.js
test/middleware.test.js
test/utils/getFilenameFromUrl.test.js
test/utils/getPossibleFilePaths.test.js

There was a lot of wrong logic:
- `request.url` is always `/path/to/file.js?foo=bar#hash`, so it is unnecessary to check on `host`
- we should avoid check on the `host` because it is middleware, we don't know what hosts a developer what to use, it should be done on application side (we already do it in webpack-dev-server)
- memorize the `parse`, no need parse multiple times same urls
- remove invalid tests
- refactor tests
- new tests
- when you use multi-compiler mode you can use same "publicPath" but difference "output.path" and versa vise, so we need return array of possible files, also some a child compiler can not have "publicPath"
- rename to `getPossibleFilePaths`
Yes, there are a lot of fixes + remove `getPossibleFilePaths` from API, it is doesn't have sense to …

Refactor code

---

package-lock.json
package.json

Make CI pass (lint task runs `npm audit`). EDIT: almost. 7 vulnerabilities left.
Regenerated `package-lock.json` from scratch, which fixed most of `npm audit`'s alerts.
*master*: `found 3251 vulnerabilities (3223 low, 28 moderate) in 1217689 scanned packages`
*PR*: `found 7 low severity vulnerabilities in 1217691 scanned packages`
None.

chore(dep): upgrade to latest stable

---

src/index.js
src/middleware.js
test/middleware.test.js

I think that the `mimeType` option should take priority over existing, known mime types. Otherwise, specifying a `mimeType` for something like html or js will have no effect.
Change of mimeType option priority with existing mime types

fix(middleware): change how mime type option is handled

---

src/middleware.js
test/middleware.test.js

Switch headers and mimeType handling back after it is checked whether the file is in outputFileSystem

fix(middleware): switch headers and mime types handling back after file check

---

src/utils/handleRangeHeaders.js
test/utils/handleRangeHeaders.test.js

refactor: use express recommended api

---

test/middleware.test.js

simple test on `publicPath: 'auto'`
No
No

test: `auto` value for the `publicPath` option

---

README.md
package-lock.json
src/index.js
test/api.test.js

Support new webpack API for watching
It can be bug and feature together 
No
No

fix: compatibility with webpack@5 API

---

README.md
src/options.json
test/__snapshots__/validation-options.test.js.snap
test/validation-options.test.js

fix schema for publicPath + description for options
No
No

fix: schema

---

src/middleware.js
test/middleware.test.js

Fixes #354
* Only set 'Content-Type' header if mime type is known.
* Remove testing for 'Content-Type' of unknown types.
* Do not test against `application/octet-stream'.
Unknown media types should have content-type blank. Because
frameworks handle Content-Types differently, it is not possible to
standardize testing at the moment. Tests against
`application/octet-stream` can create false positives with Express
because of this.
https://tools.ietf.org/html/rfc7231#section-3.1.1.5
https://github.com/broofa/mime/issues/139
Unknown mime types (no extension or unknown extension) no longer produce a `Content-Type` with Connect/NodeJS API.
https://tools.ietf.org/html/rfc7231#section-3.1.1.5
https://github.com/broofa/mime/issues/139

fix: skip content-type header on unknown types

---

src/utils/setupHooks.js
test/__snapshots__/logging.test.js.snap.webpack4
test/__snapshots__/logging.test.js.snap.webpack5
test/fixtures/webpack.array.one-error-one-warning-one-no.js
test/fixtures/webpack.array.one-error-one-warning-one-object.js
test/fixtures/webpack.no-stats.config.js
test/logging.test.js

fixes #815 fixes #813
No
Compatibility with stats for webpack@4

fix: compatibility with webpack@4

---

README.md
src/middleware.js
src/options.json
test/__snapshots__/validation-options.test.js.snap.webpack4
test/__snapshots__/validation-options.test.js.snap.webpack5
test/middleware.test.js
test/validation-options.test.js

Headers can now accept fn
no
Fix #890 fix https://github.com/webpack/webpack-dev-middleware/pull/892

feat: allow headers to accept fn

---

package-lock.json
package.json
src/options.json
test/__snapshots__/validation-options.test.js.snap.webpack4
test/__snapshots__/validation-options.test.js.snap.webpack5

output more information on errors - links to documentation and descriptions.
No
No

fix: output more information on errors

---

.github/workflows/nodejs.yml

remove manual cache step in favor of `setup-node` cache.
https://github.com/webpack/webpack-dev-middleware/blob/50b2b8694d66e47bd050bc61b4d959577063ae5a/.github/workflows/nodejs.yml#L71
None
No

ci: remove manual cache step in favor of setup-node cache

---

package-lock.json
package.json
src/utils/getFilenameFromUrl.js
test/middleware.test.js

fixes #968
No
just simple version of memorize

fix: reduced package size by removing `mem` package

---

README.md
src/middleware.js
src/options.json
test/__snapshots__/validation-options.test.js.snap.webpack4
test/__snapshots__/validation-options.test.js.snap.webpack5
test/middleware.test.js
test/validation-options.test.js

allow array for headers option:-
```js
headers: [
{
key: "X-Foo",
value: "value1",
},
{
key: "X-Bar",
value: "value2",
},
],
```
None
No

feat: allow array for `headers` option

---

src/utils/compatibleAPI.js

Fix the intention of the code 
None

Don't hardcode "range" in getHeaderFromResponse

---

src/utils/getFilenameFromUrl.js
src/utils/setupWriteToDisk.js
test/middleware.test.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None

chore: replace deprecated String.prototype.substr()

---

package-lock.json
package.json
types/index.d.ts

Fix https://github.com/webpack/webpack-dev-middleware/issues/1194
None
No

fix: types

---

package-lock.json
package.json
types/index.d.ts

chore(deps): update

---

src/options.json
test/__snapshots__/validation-options.test.js.snap.webpack5

Fix schema. `minLength` is the correct property.
No.
No.

fix: update schema for `index` and `methods` properties

---

README.md

The usage of dev middleware context is mentioned incorrectly in documentation, currently its usage is defined as `devMiddleware.context.stats ` whereas it should be `devMiddleware.stats `.
No breaking changes.
Fixes https://github.com/webpack/webpack-dev-middleware/issues/1383

docs(readme): correct dev middleware context usage

---

README.md
src/index.js
src/middleware.js
src/options.json
test/middleware.test.js
types/index.d.ts

fixes https://github.com/webpack/webpack-dev-middleware/issues/1114
No
No

feat: `mimeTypeDefault`

---

README.md
src/index.js
src/middleware.js
src/options.json
test/__snapshots__/validation-options.test.js.snap.webpack5
test/helpers/isWebpack5.js
test/middleware.test.js
test/utils/getPaths.test.js
test/validation-options.test.js
types/index.d.ts

fixes https://github.com/webpack/webpack-dev-middleware/issues/309
No
No

feat: added `modifyResponseData` option

---

src/utils/setupWriteToDisk.js
test/utils/setupWriteToDisk.test.js

We don't support webpack v4, so we don't this code anymore
Above
No
No

refactor: remove outdated code

---

src/utils/setupOutputFileSystem.js
test/middleware.test.js

Don't use `memory-fs` when `writeToDisk` is `true`, because it doesn't make sense to write in memory and on disk, due to this some plugins like `option.clean` (we use a plugin under the hood) and other can be broken
partial https://github.com/webpack/webpack-dev-middleware/issues/861
theoretically it can break some exotic cases when you use non public things, but should not
No

fix: don't use `memory-fs` when `writeToDisk` is `true`

---

package-lock.json
package.json
src/index.js
test/middleware.test.js
types/index.d.ts

fixes https://github.com/webpack/webpack-dev-middleware/issues/1674
Yes due https://github.com/streamich/memfs/releases/tag/v4.2.0
Especial due:
- mkdirp and mkdripSync were removed, they were deprecated before. (You can pass the "recursive" flag to mkdir and mkdirSync, instead.)
Because it is a breaking change I want to increase minimum Node.js version and update our deps (will do in the next PR)
Also we need update it in webpack-dev-server (and do a major release, I will try to do it soon)

chore: update memfs

---

.cspell.json
package-lock.json
package.json
src/utils/compatibleAPI.js
src/utils/escapeHtml.js
test/middleware.test.js
test/utils/escapeHtml.test.js
types/utils/escapeHtml.d.ts

Cleanup streams and handle stream errors
No
No

fix: cleaup stream and handle errors

---

src/index.js
src/middleware.js
src/utils/compatibleAPI.js
src/utils/getFilenameFromUrl.js
test/middleware.test.js
types/index.d.ts
types/utils/compatibleAPI.d.ts
types/utils/getFilenameFromUrl.d.ts

refactor: code

---

.cspell.json
src/middleware.js
src/utils/compatibleAPI.js
src/utils/getFilenameFromUrl.js
test/middleware.test.js
types/utils/getFilenameFromUrl.d.ts

fix(security): do not allow to read files above

---

src/utils/compatibleAPI.js
test/middleware.test.js

A regression was introduced in the latest version wherein files with zero bytes would have their `ContentLength` erroneously set to `1`. This resulted in requests failing with an `ERR_CONTENT_LENGTH_MISMATCH`.

fix: `ContentLength` incorrectly set for empty files

---

package-lock.json
src/index.js
src/middleware.js
src/utils/compatibleAPI.js
src/utils/getFilenameFromUrl.js
src/utils/getPaths.js
src/utils/ready.js
src/utils/setupHooks.js
src/utils/setupOutputFileSystem.js
src/utils/setupWriteToDisk.js
types/index.d.ts
types/middleware.d.ts
types/utils/compatibleAPI.d.ts
types/utils/getFilenameFromUrl.d.ts
types/utils/getPaths.d.ts
types/utils/ready.d.ts
types/utils/setupHooks.d.ts
types/utils/setupOutputFileSystem.d.ts
types/utils/setupWriteToDisk.d.ts

fix(types): make types better

---

src/middleware.js
src/utils/compatibleAPI.js
types/utils/compatibleAPI.d.ts

refactor: avoid unnecessary inner pseudo API

---

README.md
src/index.js
src/middleware.js
src/options.json
test/__snapshots__/validation-options.test.js.snap.webpack5
test/middleware.test.js
test/validation-options.test.js
types/index.d.ts

feat: support `Last-Modified` header generation

---

src/middleware.js

fix logic for security problem
No
No

fix: security problem

---

src/index.js
src/middleware.js
src/utils/getFilenameFromUrl.js
types/index.d.ts

Also added TODO for the next major release, we don't make a redirect when make `/public/file.ext` request and when `file.ext` is the file, it is a rare case, but will be great to fix it in future
No
No

refactor: better types

---

src/utils/memorize.js

In 7.2.0 console.log was left unintentionally, I assume. Here is a one-liner with the fix.

Removed cache key logging (closes #1804)

---

package-lock.json
types/index.d.ts
types/middleware.d.ts
types/utils/compatibleAPI.d.ts
types/utils/etag.d.ts
types/utils/getFilenameFromUrl.d.ts
types/utils/getPaths.d.ts
types/utils/memorize.d.ts
types/utils/ready.d.ts
types/utils/setupHooks.d.ts
types/utils/setupOutputFileSystem.d.ts
types/utils/setupWriteToDisk.d.ts

fixe https://github.com/webpack/webpack-dev-middleware/pull/1880
No
No

chore: fix types

---

package-lock.json
package.json
src/index.js
src/utils/compatibleAPI.js
src/utils/getFilenameFromUrl.js
types/index.d.ts
types/utils/compatibleAPI.d.ts

refactor: types

---

src/middleware.js
src/utils/getPaths.js
src/utils/ready.js
src/utils/setupHooks.js
src/utils/setupOutputFileSystem.js
src/utils/setupWriteToDisk.js
test/__snapshots__/logging.test.js.snap.webpack5
test/fixtures/webpack.array.dev-server-false.js
test/logging.test.js
test/middleware.test.js
test/utils/setupOutputFileSystem.test.js

ref https://github.com/webpack/webpack-cli/pull/4045/
No
When you have `devServer: false` in your multi comiler mode we will just watch and do not server, so you can use something like:
```js
const path = require("path");
module.exports = [
{
target: "webworker",
mode: "development",
entry: "./workers/worker.js",
output: {
path: path.resolve(__dirname, `public`),
},
devServer: false,
},
{
devtool: false,
mode: "development",
entry: "./entries/entry1.js",
output: {
path: path.resolve(__dirname, `static`),
publicPath: "/static/"
},
devServer: {
host: "localhost",
},
},
];
```
Useful when you have something what should just bundle and handle like static content - https://expressjs.com/en/starter/static-files.html

Fix support dev server false

---

README.md
src/index.js
src/middleware.js
src/options.json
test/middleware.test.js
types/index.d.ts

allow to configure the `Cache-Control` header
No
We can always generate `immutable` for hashed assets, webpack already set this value for asset, will be implemented later

feat: allow to configure the `Cache-Control` header

---

src/utils/getFilenameFromUrl.js

Rspack does not yet support assetsInfo, so we may need to check if assetsInfo exists.
related pr: #1924 
related issues: https://github.com/web-infra-dev/rspack/issues/7614 https://github.com/web-infra-dev/rspack/issues/7618

fix: assetsInfo may be undefined

---

src/index.js
src/middleware.js
src/utils/compatibleAPI.js
src/utils/getFilenameFromUrl.js
test/middleware.test.js
types/index.d.ts
types/utils/compatibleAPI.d.ts

fixes https://github.com/webpack/webpack-dev-middleware/issues/1920
No
We don't generate `500` because you can use multiple dev middlewares

fix: no crash when headers are already sent

---

src/index.js
src/middleware.js
src/utils/compatibleAPI.js
test/middleware.test.js
types/utils/compatibleAPI.d.ts

fixes - https://github.com/webpack/webpack-dev-middleware/issues/2150
Technically yes, but doing something after request was sent or errors is mostly a bug, so this change is a fix
No

fix: do not call the next middleware when request is finished or errored
