webpack/webpack-dev-middleware

- README.md
- middleware.js
This is a duplicate of https://github.com/webpack/webpack-dev-middleware/pull/56 but using the ready function as @sokra suggested.
@jantimon deserves credit for the code but I'd like this feature in asap as I need it for building Electron apps locally.
> waitUntilValid function using ready function

- middleware.js
should get filename from request path.
> get filename from url path

- README.md
- test/Server.test.js
Fix the SSR test issue mentioned in #121 and clarify the behavior in README.
> Fix SSR test

- README.md
Just a small fix to add a comma :).
> fix syntax in example usage

- .travis.yml
- test/Server.test.js
This adds Node 7 to the Travis CI config for builds
No tests needed
**Summary**
Node 7.x is the current stable. 
Nope 
None
> adding node 7 to travis config

- package.json
> chore(package): update `peerDependencies` (`webpack v3.0.0`)

- .travis.yml
> add node 8 for travis test

- README.md
README update to fix a small typographical error.
No, the pull request is a documentation/text fix.
**Summary**
While reading the README, I noticed a typo. So I fixed the typo.
It introduces no code changes.
This library is awesome, I wish I could contribute something more meaningful!
> Fix typo in README: confiugrations -> configurations

- package.json
bugfix
not require
**Summary**
Just update `mime` package to avoid security problem
No
Rel: https://david-dm.org/webpack/webpack-dev-middleware
> fix: update `mime` package to avoid security vulnerability

- README.md
Updated spelling error in readme.
> (sp) Update Readme

- README.md
Edit README.md
No
**Summary**
In options, `index` and `logTime` differ in font size from the other options.
So, I edited markdown grammar.
No
> Edit markdown grammar in README.md

- README.md
docs
github preview
**Summary**
Links are broken right now, and loglevel is not used anywhere anymore
no
> Fix links to source and describe webpack-log

- README.md
A documentation/examples fix
n/a
**Summary**
Examples were broken in README
No
> Fix a repeated typo in README.md

- lib/context.js
refactoring(short code)
No, all tests passed
**Summary**
Make it better
No
Nothing
> perf: Delete unnecessary condition

- appveyor.yml
Adds a configuration file for AppVeyor
We'll see if that's needed based on the output from the AppVeyor tests
**Summary**
After running into some Windows-only bugs that were introduced in v3.0.0, it became obvious that we need to run some tests against Windows in CI.
No
> Add Appveyor Config

- README.md
fix: missing right parenthesis
No need
**Summary**
fix: missing right parenthesis
No
> docs(readme): fix missing right parenthesis

- package-lock.json
- package.json
> chore(package): add `release` script (`scripts`)

- package-lock.json
- package.json
This PR fixes all non-semver major security vulnerabilities reported by `npm audit`, there were 24 in total but the rest requires semver major updates
> fix(package): 18 security vulnerabilities

- lib/fs.js
- package-lock.json
- package.json
> chore(package): update `webpack-log` v1.2.0...2.0.0

- README.md
> docs(readme): fix `writeToDisk` example

- appveyor.yml
ci
not required
**Summary**
add node@11 on windows
No
No
> ci: node@11 test on windows

- .travis.yml
ci
not required
**Summary**
Test on all lts versions
No
No
> ci: test on all lts node version on linux

- lib/fs.js
refactor
exists
**Summary**
no
no
> refactor: consistent write to fs

- .travis.yml
- appveyor.yml
ci
Not requred
**Summary**
Improve CI
No
No
> ci: improve

- appveyor.yml
- lib/fs.js
- package-lock.json
- package.json
chore
exists
**Summary**
Update deps and some improve on CI - we use `fast_finish` - i.e. if tests failed on node@6 we don't need run tests on node@8 and up
No
No
> chore(deps): update

- .github/CODEOWNERS
chore
no
**Summary**
I added myself to codeowners to be included in the review.
michael-ciniawsky is inactive for a long time.
> chore(github): add hiroppy to CODEOWNERS

- lib/util.js
Refactored the respective code block to a more concise form.
N/A
N/A
> chore: Minor refactor

- package-lock.json
- package.json
- test/server.test.js
> chore: update deps

- lib/fs.js
- package-lock.json
- package.json
- test/server.test.js
fixes #469
No
Need refactor test, let's do it in future
Need fix compatibility with webpack@5, i will do it in next PR
> fix: memory leak when `writeToDisk` used

- package-lock.json
- package.json
- renovate.json
closes: #484 
Ignore cross-env because it doesn't support Node@6.
> chore(deps): update some devDependencies

- azure-pipelines.yml
- babel.config.js
- package.json
I created the `next` branch and dropped Node@6.
> chore: drop Node@6, 8

- package.json
> chore(package.json): fix typo

- package-lock.json
- package.json
- src/index.js
- src/options.json
- test/fixtures/simple-config/foo.js
- test/fixtures/simple-config/webpack.config.js
- test/validation-options.test.js
> feat: make use of schema-utils

- package-lock.json
- package.json
- src/utils/setupWriteToDisk.js
Remove unnecessary dep
No
Because we support only `>= 10.13` we can safely use this method
> Refactor migrate on mkdir

- README.md
- src/options.json
- src/utils/setupOutputFileSystem.js
- test/file-system.test.js
- test/validation-options.test.js
We forgot change `fs` in schema and some places
No, because we already change this in documentation and in many places into code base
No, my mistake
> Chore fix output file system

- README.md
- azure-pipelines.yml
- package-lock.json
- package.json
- src/utils/setupOutputFileSystem.js
- test/middleware.test.js
- test/validation-options.test.js
migrate on memfs, other branch is broken
Yes, now we use `memfe` instead `memory-fs`
fixes #405
> feat: migrate on `memfs`

- src/middleware.js
We never support koa officially, also we don't have tests for koa, and don't have plan to support that
Yes, koa is not supported anymore
Also increase coverage
> refactor: use send express method

- src/index.js
- src/utils/setupHooks.js
- test/api.test.js
- test/helpers/getCompilerHooks.js
- test/middleware.test.js
Now all tests refactored
No
Next PR will remove `lazy` and then PR to up coverage, don't want waste time on test option will be removed
> Refactor more test

- package-lock.json
> chore(deps): update lock file

- README.md
> test: more and refactor

- src/index.js
- src/middleware.js
- src/utils/getFilenameFromUrl.js
- src/utils/setupOutputFileSystem.js
- test/utils/getFilenameFromUrl.test.js
Use `context` everywhere for simplify code
No
No
> Refactor use context everywhere

- src/utils/setupWriteToDisk.js
I think we should return logging here for debug purpose, also let's use full path to file to avoid misleading real file location
No
I will add more tests in near future, we have some bugs with `invalid` hook - we don't handle that
> Feat improve logging for the write to disk option

- src/index.js
- src/options.json
- test/__snapshots__/validation-options.test.js.snap
- test/fixtures/server-test/webpack.array.watch-options.config.js
- test/fixtures/server-test/webpack.watch-options.config.js
- test/middleware.test.js
- test/validation-options.test.js
Respect `watchOptions` from configuration instead option
Yes
No
> refactor: remove the `watchOptions` option

- src/middleware.js
- test/middleware.test.js
prepare for #350 
In theory yes, but i think it is more bug fix, because we created invalid the `Content-type` header
+ test for unknown `Content-type`
> Refactor tests for issue 350

- src/index.js
- src/utils/setupHooks.js
- test/__snapshots__/middleware.test.js.snap
- test/fixtures/webpack.simple.config.js
- test/helpers/GetLogsPlugin.js
- test/helpers/getCompilerHooks.js
- test/middleware.test.js
- more tests
- fix name of hook, we don't need `webpack` prefix
- remove unnecessary hook `run`, we never call them, because we use `watch`.
- refactor
Potential yes - renaming name of hooks
No
> refactor: hooks

- src/utils/setupWriteToDisk.js
- test/__snapshots__/middleware.test.js.snap
- test/middleware.test.js
Refactor test + concurrence for the `writeToDisk` option
No
No
> refactor: tests

- test/__snapshots__/middleware.test.js.snap
- test/middleware.test.js
Latest big test refactor
No
Next PRs and we ready for release next (rc):
- up coverage to 100%
- fix bug when developer uses `[hash]` in `output.path`
- send `context` to callbacks instead `stats` for better development experience
- respect publicPath from configuration
> refactor: test

- test/middleware.test.js
> Test increase coverage

- README.md
- src/index.js
- src/middleware.js
- src/utils/getFilenameFromUrl.js
- src/utils/setupLogger.js
- test/middleware.test.js
Last refactor, use context everywhere, simplify code in some places, use `rest.locals.webpack.devMiddleware` to provide context
Yes, will be in changelog
No
> refactor: code

- CHANGELOG.md
- package-lock.json
- package.json
rc release
No
/cc @hiroppy @Loonride please check my changelog, maybe I forgot something
> chore(release): 4.0.0-rc.0

- package.json
> fix: missing the `options.json` file

- lint-staged.config.js
Delete git add.
see https://github.com/okonet/lint-staged#migration
no
> chore(lint-staged): remove git add

- .github/workflows/nodejs.yml
> ci: add node@14 and remove v13

- src/middleware.js
- src/utils/handleRangeHeaders.js
- test/middleware.test.js
- test/utils/__snapshots__/handleRangeHeaders.test.js.snap
- test/utils/__snapshots__/setupHooks.test.js.snap
- test/utils/__snapshots__/setupWriteToDisk.test.js.snap
- test/utils/handleRangeHeaders.test.js
- test/utils/ready.test.js
- test/utils/setupHooks.test.js
- test/utils/setupOutputFileSystem.test.js
- test/utils/setupWriteToDisk.test.js
Adding tests for util files
Yes, breaking API change for handleRangeHeaders util
> chore(utils): add utils tests

- package.json
> chore: support webpack@5

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/index.js
- src/utils/getFilenameFromUrl.js
- test/__snapshots__/middleware.test.js.snap
- test/helpers/GetLogsPlugin.js
- test/middleware.test.js
- test/utils/getPaths.test.js
update deps + ci + tests
No
No
> Refactor next

- package-lock.json
- package.json
use webpack@5 by default + update babel
No
No
> chore: switch on webpack@5 by default

- package.json
- src/cjs.js
- test/cjs.test.js
fixes #652
In theory yes, but for people who use `rc`
I will add this in chagelog
> fix: cjs import

- README.md
Document use (for now) with Fastify while #617 is worked on - addresses concerns raised in #602 .
This also can serve as a location in the README for documentation on other servers once #617  is merged.
> docs: add information on use with fastify

- test/__snapshots__/middleware.test.js.snap
- test/api.test.js
- test/middleware.test.js
prepare tests for other frameworks
No
No
> test: prepare tests for other frameworks

- src/middleware.js
> fix: compatibility with set headers option

- package-lock.json
- package.json
- test/helpers/isWebpack5.js
- test/helpers/listenAndCompile.js
- test/validation-options.test.js
Update this package and modify some code.
no
> chore(deps): update eslint-config-prettier

- package.json
> fix: peer dependencies with webpack@5

- README.md
> docs: fix example in readme

- .github/workflows/nodejs.yml
Update workflow: -
-  cache node-modules
-  don't install webpack-5 twice.
None.
None
> build: update node.js workflow

- renovate.json
Ignore `node` for renovate bot.
None
No
> chore: use constraint and ignore node for renovate-bot

- jest.config.js
- scripts/globalSetup.js
- test/helpers/snapshotResolver.js
Don't print the webpack version on each test, It's kind of spammy. 
None
No
> chore: don't print webpack version for each test

- .husky/commit-msg
> fix: husky config

- .github/workflows/nodejs.yml
- lint-staged.config.js
fix some weird configurations
No
No
> chore: small tweak

- .github/workflows/nodejs.yml
- babel.config.js
- package-lock.json
- package.json
> build: drop node v10

- .github/workflows/nodejs.yml
> chore: update commitlint action in CI

- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
> docs: update issue templates

- .github/workflows/nodejs.yml
CI failing for node 16.
https://bugs.chromium.org/p/v8/issues/detail?id=12188
None
No
> ci: fix node.js because of v8 bug

- test/middleware.test.js
> test: use async API

- package-lock.json
- package.json
- src/utils/setupHooks.js
- test/logging.test.js
migrate to `nanocolors` from `colorette`.
None
No
> chore: migrate to `nanocolors`

- .github/workflows/nodejs.yml
- package-lock.json
bump deps + test on Node.js v17
No
No
> ci: added Node.js version 17

- README.md
Fix https://github.com/webpack/webpack-dev-middleware/issues/1112
None
No
> docs: fix `outputFileSystem` and `stats` usage

- .github/workflows/nodejs.yml
Use node v16 for lint job
None
No
> ci: use node v16 for lint job

- .eslintrc.js
- src/index.js
- src/utils/setupOutputFileSystem.js
- test/helpers/snapshotResolver.js
enable `reportUnusedDisableDirectives` for eslint.
None
No
> chore: enable `reportUnusedDisableDirectives` for eslint

- lint-staged.config.js
update the lint-staged config to run prettier for all files and use eslint cache.
None
No
> chore: update `lint-staged` configuration

- package-lock.json
- package.json
- src/index.js
- src/middleware.js
- src/utils/compatibleAPI.js
- src/utils/getFilenameFromUrl.js
- src/utils/getPaths.js
- src/utils/ready.js
- src/utils/setupHooks.js
- src/utils/setupOutputFileSystem.js
- src/utils/setupWriteToDisk.js
- test/api.test.js
- tsconfig.json
- types/cjs.d.ts
- types/index.d.ts
- types/middleware.d.ts
- types/utils/compatibleAPI.d.ts
- types/utils/getFilenameFromUrl.d.ts
- types/utils/getPaths.d.ts
- types/utils/ready.d.ts
- types/utils/setupHooks.d.ts
- types/utils/setupOutputFileSystem.d.ts
- types/utils/setupWriteToDisk.d.ts
Add types
No
We need drop cjs wrapper for valid types, I will do it in the other PR
> Feat added types

- package.json
- src/cjs.js
- src/index.js
- src/middleware.js
- src/utils/getFilenameFromUrl.js
- src/utils/getPaths.js
- src/utils/ready.js
- src/utils/setupHooks.js
- src/utils/setupOutputFileSystem.js
- src/utils/setupWriteToDisk.js
- test/cjs.test.js
- test/helpers/runner.js
- test/utils/setupOutputFileSystem.test.js
- types/cjs.d.ts
- types/index.d.ts
- types/middleware.d.ts
- types/utils/getFilenameFromUrl.d.ts
- types/utils/getPaths.d.ts
- types/utils/ready.d.ts
- types/utils/setupHooks.d.ts
- types/utils/setupOutputFileSystem.d.ts
- types/utils/setupWriteToDisk.d.ts
remove cjs wrapper
Potentially yes, but we use babel and out code in commonjs format, but typescript generates ESM, it is bug
No
> feat: remove cjs wrapper

- src/utils/setupOutputFileSystem.js
> chore: fix lint warning

- .github/workflows/nodejs.yml
Update workflow. Only one job for webpack-4.
No
No
> ci: update workflow strategy

- package-lock.json
- package.json
> chore: udpate `webpack`

- .github/workflows/nodejs.yml
Add job to check `types`.
None
No
> ci: add job to check `types`

- package-lock.json
- package.json
force update memfs to avoid Node.js v18 problems
No
No
> chore(deps): memfs

- README.md
> docs: remove deps badge

- README.md
Use latest syntax.
> **Warning**
>
> _We do not recommend installing this module globally._
No
No
> docs: update note to use the latest syntax

- README.md
Fix https://github.com/webpack/webpack-dev-middleware/pull/1356
> docs: update headers usage in README

- .github/workflows/nodejs.yml
- babel.config.js
- package-lock.json
- package.json
Drop Nodejs v12
BREAKING CHANGE: minimum supported Nodejs version is 14.15.0
No
> build: minimum supported Nodejs version is 14.15.0

- .github/workflows/nodejs.yml
- babel.config.js
- package-lock.json
- package.json
Prepare for the next major version.
Yes.
No
> feat!: next

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/utils/setupHooks.js
- src/utils/setupOutputFileSystem.js
- test/middleware.test.js
- test/utils/setupOutputFileSystem.test.js
- types/utils/setupHooks.d.ts
Drop webpack v4
minimum supported webpack version is 5.0.0
> feat!: minimum supported webpack version is 5.0.0

- package-lock.json
- package.json
> chore: update typescript to v4.9.3

- .github/workflows/nodejs.yml
No
Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.
None
No
> ci: use LTS node version in workflows

- package-lock.json
- package.json
same as https://github.com/webpack/webpack-dev-server/pull/4778
No
> fix: make webpack optional peerDep

- package-lock.json
- src/middleware.js
- src/utils/setupHooks.js
don't load unnecessary packages when we don't need
No
No
> Faster startup time

- src/index.js
- types/index.d.ts
> fix(types): `methods` should be string array

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
use GitHub discussions instead of Gitter in issue templates
NO
no
> docs: use GitHub discussions instead of Gitter in issue templates

- .github/workflows/nodejs.yml
update commitlint-github-action to v5
No
No
> ci: update commitlint-github-action to v5

- .github/workflows/nodejs.yml
- README.md
- package-lock.json
- package.json
- src/index.js
- src/middleware.js
- src/utils/getFilenameFromUrl.js
- src/utils/getPaths.js
- src/utils/setupHooks.js
- src/utils/setupOutputFileSystem.js
- src/utils/setupWriteToDisk.js
- test/api.test.js
- test/helpers/snapshotResolver.js
- test/logging.test.js
- test/middleware.test.js
- test/utils/setupWriteToDisk.test.js
- types/index.d.ts
- types/middleware.d.ts
- types/utils/compatibleAPI.d.ts
- types/utils/getFilenameFromUrl.d.ts
- types/utils/getPaths.d.ts
- types/utils/ready.d.ts
- types/utils/setupHooks.d.ts
- types/utils/setupOutputFileSystem.d.ts
- types/utils/setupWriteToDisk.d.ts
Minimum supported Node.js version is 18.12.0
Yes
Update some deps, jest still bad with ESM, so I will try to migrate our tests to ESM in future
> chore!: minimum supported Node.js version is 18.12.0

- .github/workflows/nodejs.yml
> ci: fix lint commits

- src/utils/getFilenameFromUrl.js
- test/middleware.test.js
Improve perf + more tests (we can run them not only on windows)
No
No
> fix: improve perf

- package-lock.json
- src/middleware.js
- src/utils/compatibleAPI.js
- src/utils/getFilenameFromUrl.js
- types/utils/compatibleAPI.d.ts
- types/utils/getFilenameFromUrl.d.ts
backport fix for the security problem
No
No
> fix(security): do not allow to read files above

- README.md
- package-lock.json
- package.json
- src/index.js
- test/api.test.js
- test/middleware.test.js
- types/index.d.ts
Built-in hapi support using `webpackDevMiddleware.hapiPlugin()`
No
No
> Feat hapi support

- test/middleware.test.js
> test: refactor

- .github/workflows/nodejs.yml
> ci: add Node v22

- README.md
> docs: update GitHub markdown note syntax in README.md

- .github/workflows/nodejs.yml
- package-lock.json
- src/middleware.js
- types/index.d.ts
- types/utils/compatibleAPI.d.ts
- types/utils/ready.d.ts
fixes https://github.com/webpack/webpack-dev-middleware/pull/1992
No  
No
> chore(deps): bump

- .github/workflows/dependency-review.yml
Update dependency-review-action to v4
NA
NA
> ci: update dependency-review-action

- .github/workflows/nodejs.yml
- package-lock.json
> ci: node v24 windows

- package-lock.json
- package.json
- setupTest.js
- src/middleware.js
> chore: bump config

- test/middleware.test.js
> test: fix stability

- package-lock.json
- package.json
fixes - https://github.com/webpack/webpack-dev-middleware/issues/2171
No
Nothing
> fix: unpin memfs
